package Vista;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;



public class FrmLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Login - ADAVAMINSA");
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Vista/Imagenes/icono_adavaminsa.ico"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Base = new javax.swing.JPanel();
        Panel_Datos = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        cbxRol = new javax.swing.JComboBox<>();
        btnIngresar = new javax.swing.JButton();
        lblRol = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(367, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(367, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Datos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panel_Datos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/avatar.gif"))); // NOI18N
        Panel_Datos.add(lblAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 90, 90));

        lblUsuario.setText("Usuario:");
        Panel_Datos.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        lblContraseña.setText("Contraseña:");
        Panel_Datos.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        Panel_Datos.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 130, -1));
        Panel_Datos.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 130, -1));

        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administradora", "Almacén", "Coordinadora" }));
        Panel_Datos.add(cbxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 130, -1));

        btnIngresar.setText("Iniciar Sesión");
        Panel_Datos.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        lblRol.setText("Rol:");
        Panel_Datos.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 30, -1));

        Base.add(Panel_Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 240, 340));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/X1.gif")));
        btnSalir.setOpaque(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setBorderPainted(false);
        btnSalir.setFocusPainted(false);
        Base.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 35, 35));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/logo_adavaminsa.png"))); // NOI18N
        Base.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/fondo_adavaminsa.png"))); // NOI18N
        Base.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 500));
        Base.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 370, 510));

        getContentPane().add(Base, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Panel_Datos;
    public javax.swing.JButton btnIngresar;
    public javax.swing.JButton btnSalir;
    public javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblUsuario;
    public javax.swing.JPasswordField txtContraseña;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
